### ISSUE TITLE
[Resolved] Failed to load on Chrome - Windows 10

### ISSUE THREAD

**Issue by BritishBenji** [refact0r/startpage#4]
Error received:
```
Invalid value for overriding homepage url: '[index.html]'.
Could not load manifest.
```

Chrome Version: `Version 104.0.5112.81 (Official Build) (64-bit)`

Steps taken:
- Clone repository
- Install Cascadia Code (from given link)
- Restart machine
- Open `chrome://extensions`
- Click Load Unpacked
- Select `.\startpage\public`

**Comment by refact0r** [comment]
It seems like the solution is to remove lines 9-11 from `public/manifest.json`:
```json
"chrome_settings_overrides": {
    "homepage": "index.html"
},
```
Can you verify that this works?

**Comment by BritishBenji** [comment]
My apologies for the wait

This has allowed me to load the extension into Chrome perfectly and replaces my New Tab page

And issue now occurs where nothing shows in the tab (other than the title, favicon, and a black/grey background), in the console, we have the errors:
```
GET chrome-extension://<extensionID>/build/bundle.css net::ERR_FILE_NOT_FOUND
index.html:15          
GET chrome-extension://<extensionID>/build/bundle.js net::ERR_FILE_NOT_FOUND
```
(extension ID's have been replaced to make easier to see)

If this requires it's own, separate GitHub issue, lmk

**Comment by refact0r** [comment]
Please run 
```
npm install
```
and then
```
npm run build
```
in the root directory. This will generate the necessary javascript and css files.

Sorry, I forgot to include these files in the repo. I will update it now.

**Comment by BritishBenji** [comment]
Works a charm, thank you!
